#!/bin/sh

export ZDOTDIR="${HOME}/.zdot/"

#xset r rate 275 30
#setxkbmap dvorak -option ctrl:swapcaps
#setxkbmap dvorak
xset -b
#export EDITOR="emacsclient"

#export XMODIFIERS="@im=ibus"
#export GTK_IM_MODULE="ibus"
#export QT_IM_MODULE="xim"
#ibus-daemon -d -x

#export XMODIFIERS=@im=SCIM
#export GTK_IM_MODULE=scim
#export QT_IM_MODULE=scim
#scim -d

export XMODIFIERS=@im=uim
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
uim-xim &
uim-toolbar-gtk-systray &
#uim-toolbar-qt4 &

export LANG='en_US.utf8'
#export LC_MESSAGES='en_US.utf8'

#wpa_gui -t &
#pasystray &
