#!/bin/zsh
# -*- mode: shell-script -*-

UPDATE_SYSTEMD=0

## skip environment update if it is not necessary.
if [[ ! -z "${NEED_UPDATE_ENV}" && "${NEED_UPDATE_ENV}" -eq 0 ]]; then
return
fi

register_systemd() {
if [[ "${UPDATE_SYSTEMD}" -ne 0 ]]; then
systemctl --user import-environment "$1"
fi
}

typeset -x LANG
LANG=en_US.UTF-8
register_systemd LANG

## avoid interfere with TRUMP on emacs
if [[ "$TERM" = "dumb" ]]; then
unset RPROMPT
unset RPS1
PS1="$ "
unsetopt zle
unsetopt rcs  # Inhibit loading of further config files
fi

typeset -U fpath path manpath
typeset -TU INFOPATH infopath
fpath=(~/.local/share/zsh(N-/) ${fpath[@]} ~/.linuxbrew/share/zsh/site-functions(N-/))
path=(~/.local/*/bin(N-/) ~/.local/bin(N-/) ${path[@]} ~/.linuxbrew/bin(N-/) ~/.linuxbrew/sbin(N-/))
manpath=(~/.local/*/share/man(N-/) ~/.local/share/man(N-/) ${manpath[@]} ~/.linuxbrew/share/man(N-/))
infopath=(~/.local/*/share/info(N-/) ~/.local/share/info(N-/) ${infopath[@]} ~/.linuxbrew/share/info(N-/))

path=(/app/*/bin(N-/) /app/*(N-/) ${path[@]})
path=(~/.local/share/flatpak/exports/bin(N-/) ${path[@]})
path=(~/.gem/ruby/*/bin(N-/) ${path[@]})
path=(~/.local/google-cloud-sdk/bin(N-/) ${path[@]})

path=(~/.texlive/2021/bin/x86_64-linux(N-/) ${path[@]})
manpath=(~/.texlive/2021/texmf-dist/doc/man(N-/) ${manpath[@]})
infopath=(~/.texlive/2021/texmf-dist/doc/info(N-/) ${infopath[@]})

typeset -xTU PYTHONUSERBASE python_user_base
python_user_base=(~/.local/Python(N-/))
register_systemd PYTHONUSERBASE

typeset -xTU ANDROID_HOME android_home
android_home=(~/.local/Android/Sdk(N-/))
path=(${path[@]} ~/.local/Android/Sdk/platform-tools(N-/) ~/.local/Android/Sdk/tools(N-/))
register_systemd ANDROID_HOME

path=(~/.cargo/bin(N-/) ${path[@]})

typeset -xTU GOPATH gopath
gopath=(~/.local/go(N-/))
register_systemd GOPATH

typeset -xTU PUB_CACHE pub_cache
pub_cache=(~/.local/dart-package(N-/))
register_systemd PUB_CACHE

typeset -xTU HOMEBREW_PREFIX homebrew_prefix
homebrew_prefix=(~/.linuxbrew(N-/))
register_systemd HOMEBREW_PREFIX
typeset -xTU HOMEBREW_CELLAR homebrew_cellar
homebrew_cellar=(~/.linuxbrew/Cellar(N-/))
register_systemd HOMEBREW_CELLAR
typeset -xTU HOMEBREW_REPOSITORY homebrew_repository
homebrew_repository=(~/.linuxbrew/Homebrew(N-/))
register_systemd HOMEBREW_REPOSITORY

DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

register_systemd PATH
register_systemd INFOPATH
register_systemd MANPATH

if [ -e /home/${USER}/.nix-profile/etc/profile.d/nix.sh ]; then . /home/${USER}/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

## skip update environment variable in next shell to keep performance
typeset -x NEED_UPDATE_ENV
NEED_UPDATE_ENV=0

# set environment variable for Guix package manager
typeset -x GUIX_LOCPATH
GUIX_LOCPATH=$HOME/.guix-profile/lib/locale
