#!/bin/zsh
# -*- mode: shell-script -*-

typeset -x LANG
LANG=en_US.UTF-8

typeset -U fpath path manpath
typeset -TU INFOPATH infopath
fpath=(${fpath[@]} ~/.local/share/zsh(N-/) ~/.linuxbrew/share/zsh/site-functions(N-/))
path=(${path[@]} ~/.local/*/bin(N-/) ~/.local/bin(N-/) ~/.linuxbrew/bin(N-/) ~/.linuxbrew/sbin(N-/))
manpath=(${manpath[@]} ~/.local/*/share/man(N-/) ~/.local/share/man(N-/) ~/.linuxbrew/share/man(N-/))
infopath=(${infopath[@]} ~/.local/*/share/info(N-/) ~/.local/share/info(N-/) ~/.linuxbrew/share/info(N-/))

path=(${path[@]} /app/*/bin(N-/) /app/*(N-/))

path=(${path[@]} ~/.texlive/2019/bin/x86_64-linux(N-/))
manpath=(${manpath[@]} ~/.texlive/2019/texmf-dist/doc/man(N-/))
infopath=(${infopath[@]} ~/.texlive/2019/texmf-dist/doc/info(N-/))

typeset -xTU PYTHONUSERBASE python_user_base
python_user_base=(~/.local/python(N-/))

typeset -xTU ANDROID_HOME android_home
android_home=(~/.local/Android/Sdk(N-/))
path=(${path[@]} ~/.local/Android/Sdk/platform-tools(N-/) ~/.local/Android/Sdk/tools(N-/))

typeset -xTU GOPATH gopath
gopath=(~/.local/go(N-/))

typeset -xTU PUB_CACHE pub_cache
pub_cache=(~/.local/dart-package(N-/))

typeset -xTU HOMEBREW_PREFIX homebrew_prefix
homebrew_prefix=(~/.linuxbrew(N-/))

typeset -xTU HOMEBREW_CELLAR homebrew_cellar
homebrew_cellar=(~/.linuxbrew/Cellar(N-/))

typeset -xTU HOMEBREW_REPOSITORY homebrew_repository
homebrew_repository=(~/.linuxbrew/Homebrew(N-/))
