#!/bin/zsh
# -*- mode: shell-script -*-

typeset -x LANG
LANG=en_US.UTF-8

typeset -U fpath path manpath
typeset -TU INFOPATH infopath
fpath=(~/.local/share/zsh(N-/) ${fpath[@]} ~/.linuxbrew/share/zsh/site-functions(N-/))
path=(~/.local/*/bin(N-/) ~/.local/bin(N-/) ${path[@]} ~/.linuxbrew/bin(N-/) ~/.linuxbrew/sbin(N-/))
manpath=(~/.local/*/share/man(N-/) ~/.local/share/man(N-/) ${manpath[@]} ~/.linuxbrew/share/man(N-/))
infopath=(~/.local/*/share/info(N-/) ~/.local/share/info(N-/) ${infopath[@]} ~/.linuxbrew/share/info(N-/))

path=(/app/*/bin(N-/) /app/*(N-/) ${path[@]})

path=(~/.gem/ruby/*/bin(N-/) ${path[@]})

path=(~/.texlive/2020/bin/x86_64-linux(N-/) ${path[@]})
manpath=(~/.texlive/2020/texmf-dist/doc/man(N-/) ${manpath[@]})
infopath=(~/.texlive/2020/texmf-dist/doc/info(N-/) ${infopath[@]})

typeset -xTU PYTHONUSERBASE python_user_base
python_user_base=(~/.local/Python(N-/))

typeset -xTU ANDROID_HOME android_home
android_home=(~/.local/Android/Sdk(N-/))
path=(${path[@]} ~/.local/Android/Sdk/platform-tools(N-/) ~/.local/Android/Sdk/tools(N-/))

path=(~/.cargo/bin(N-/) ${path[@]})

typeset -xTU GOPATH gopath
gopath=(~/.local/go(N-/))

typeset -xTU PUB_CACHE pub_cache
pub_cache=(~/.local/dart-package(N-/))

typeset -xTU HOMEBREW_PREFIX homebrew_prefix
homebrew_prefix=(~/.linuxbrew(N-/))

typeset -xTU HOMEBREW_CELLAR homebrew_cellar
homebrew_cellar=(~/.linuxbrew/Cellar(N-/))

typeset -xTU HOMEBREW_REPOSITORY homebrew_repository
homebrew_repository=(~/.linuxbrew/Homebrew(N-/))
