## KeyBinding
setopt dvorak
bindkey -e
setopt no_flow_control	#For collision of keybind
bindkey '^p' history-beginning-search-backward
bindkey '^n' history-beginning-search-forward
bindkey '^[[3~' delete-char
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line

## Function of 'cd'
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
cdpath=(~)
#chpwd_functions+=dirs

## History
HISTFILE=${ZDOTDIR}/.zsh_history
HISTSIZE=10000
SAVEHIST=1000000
setopt extended_history
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt inc_append_history
setopt share_history
setopt hist_verify

## Color
autoload -U colors
colors
export CLICOLOR=true

## Prompt
autoload -U promptinit
promptinit
#if [ $UID -eq 0 ]; then NCOLOR="red"; else NCOLOR="green"; fi
#PROMPT='%{$fg[$NCOLOR]%}%m %#%{$reset_color%} '
RPROMPT="[%c]"
setopt prompt_subst
setopt prompt_percent
setopt transient_rprompt
prompt gentoo

## Completion
autoload -U compinit
compinit
#zstyle ':completion:*' completer _oldlist _complete _match _history _ignored _approximate _prefix
#zstyle ':completion:*' format '%B%d%b'
#zstyle ':completion:*' group-name ''
#zstyle ':completion:*:default' menu select=2
#zstyle ':completion:*:default' list-colors ""
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z} r:|[._-]=*'
#zstyle ':completion:*' use-cache yes
#zstyle ':completion:*' verbose yes
zstyle ':completion:*:sudo:*' environ PATH="${SUPER_PATH}:${PATH}"
setopt auto_list
setopt complete_in_word
setopt glob_complete
setopt hist_expand
setopt no_beep
setopt numeric_glob_sort
setopt auto_remove_slash
unsetopt correct
setopt magic_equal_subst
setopt completealiases
unsetopt equals

## Correction
setopt correctall

## Expansion
setopt extended_glob
setopt mark_dirs

## Alias
alias jman='LANG=ja_JP.utf8 man'
#alias -g p="|& $PAGER"
#alias -g g='| grep'
alias r="rm -i"
alias e='emacs'
alias v='vim'
alias l='ls -lh --color=auto --show-control-chars'
alias la='ls -a'
alias s='sudo --'
alias em='sudo -E chrt -b 0 emerge --color y -a'
alias update='sudo -E chrt -b 0 nice -15 eix-sync'
alias eq='equery'
alias c='cat'

## Misc.
setopt long_list_jobs
REPORTTIME=10
WORDCHARS=${WORDCHARS:s,/,,}

