# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

setopt ignoreeof # prevent logout with Ctrl-D

HISTFILE="${XDG_STATE_HOME:-$HOME/.cache}/zsh_history"
HISTSIZE=100000
SAVEHIST=1000000
setopt inc_append_history
setopt share_history

bindkey "^[[3~" delete-char
# zinit light denysdovhan/spaceship-prompt
zinit light @'romkatv/powerlevel10k'
zinit wait lucid blockf light-mode for \
	@'zsh-users/zsh-autosuggestions' \
	@'zsh-users/zsh-completions' \
	@'zdharma-continuum/fast-syntax-highlighting' \
	@'olets/zsh-abbr' \
	atpull'asdf plugin update --all' @'asdf-vm/asdf' \
	@'romkatv/powerlevel10k'
zinit wait lucid pack"binary+keys" for fzf
zinit wait lucid light-mode as"program" from"gh-r" for \
	pick'ripgrep*/rg' @'BurntSushi/ripgrep' \
	cp'yq* -> yq' atclone'./yq shell-competion zsh > _yq' atpull'%atclone' @'mikefarah/yq' \
	pick'zq' @'brimdata/zed' \
	pick'zed' @'brimdata/zed' \
	pick'zoxide' atclone'./zoxide init zsh > init.zsh' atpull'%atclone' src'init.zsh' nocompile'!' @'ajeetdsouza/zoxide' \
	pick'ghq*/ghq' @'x-motemen/ghq'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
