[tools]
"aqua:fluxcd/flux2" = "latest"
bat = "latest"
chezmoi = "latest"
deno = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
helm = "latest"
jq = "latest"
k9s = "latest"
kompose = "latest"
kubectl = "latest"
minikube = "latest"
pnpm = "latest"
yq = "latest"
zoxide = "latest"
