;;; -*- mode: Emacs-Lisp -*- ;;;
;;; font.el --- A emacs external setting file (fontset definition)

;;; HELP SECTION
;;;  To view the list of charsets, (list-character-sets nil)
;;;  To view the list of defineded fontsets, (list-fontsets nil)

;; Make fontsets based on ascii

(let* ((fontset-name "akadori")
       (size 12)
       (asciifont "Inconsolata")
       (jpfont "VL Gothic")
       (failfont "IPAGothic")
       (weight "normal")
       (slant "normal")
       (afont (format "%s-%d:weight=%s:slant=%s" asciifont size weight slant))
       (afontspec (font-spec :family asciifont))
       (jfontspec (font-spec :family jpfont))
       (ffontspec (font-spec :family failfont))
       (fsn (create-fontset-from-ascii-font afont nil fontset-name)))
  (set-fontset-font fsn 'unicode afontspec nil 'append)
  (set-fontset-font fsn 'unicode jfontspec nil 'append)
  (set-fontset-font fsn 'unicode ffontspec nil 'append))

(let* ((fontset-name "aoshima")
       (asciifont "Inconsolata")
       (size 14)
       (weight "normal")
       (slant "normal")
       (fsn (create-fontset-from-ascii-font (format "%s-%d:weight=%s:slant=%s" asciifont size weight slant) nil fontset-name)))
  (set-fontset-font fsn 'latin (font-spec :family "Inconsolata") nil 'append)
  (set-fontset-font fsn 'kana (font-spec :family "VL Gothic") nil 'append)
  (set-fontset-font fsn 'japanese-jisx0208 (font-spec :family "VL Gothic") nil 'append)
  (set-fontset-font fsn 'japanese-jisx0213.2004-1 (font-spec :family "IPAGothic") nil 'append)
  ;(set-fontset-font fsn 'han (font-spec :family "IPAmjMincho") nil 'append)
  (set-fontset-font fsn nil (font-spec :family "Noto Sans CJK") nil 'append)
  )

(defun set-frame-fontset (fontset)
  "I cannot set fontset to the current frame with set-frame-font function.
If you want to set fontset to current frame, use set-frame-perameter instead of set-frame-font (see bug-report #11722)."
  (interactive "sfontset name: ")
  (if (string-match "^fontset-" fontset)
      (set-frame-parameter nil 'font fontset)
    (set-frame-parameter nil 'font (concat "fontset-" fontset))))

;; Rescaling
(dolist
    (elt '(("^-apple-hiragino.*" . 1.2)
	   (".*osaka-bold.*" . 1.2)
	   (".*osaka-medium.*" . 1.2)
	   (".*courier-bold-.*-mac-roman" . 1.0)
	   (".*monaco cy-bold-.*-mac-cyrillic" . 0.9)
	   (".*monaco-bold-.*-mac-roman" . 0.9)))
  (add-to-list 'face-font-rescale-alist elt))


;;; TEST SECTION
;;;  Alphabet: 0123456789abcdefABCDEF,.'";:!@#$%^&*()[]{}+-=/\~
;;;  Japanese: あア亜、。’”；：！＠＃＄％＾＆＊（）「」｛｝＋ー＝＼／〜
;;;  Japanese-JISX0208: 乱 便 啜 刧
;;;  Japanese-JISX0212: 吧 佘 巠
;;;  Japanese-XISX0213: 吞 䖝 汶 步
;;;  Japanese-IVS:(string ?辻 #xe0100) (string ?辻 #xe0101)
;;;               (insert ?邊 #xe0100 ?邊 #xe0101 ?邊 #xe0102 ?邊 #xe0103 ?邊 #xe0104)
;;;
;;;    .. ¡ (#xA0 .. #xA1)
;;; ¢ .. £ (#xA2 .. #xA3)
;;; ¤ .. ¥ (#xA4 .. #xA5)
;;; ¦ (#xA6)
;;; § .. ¨ (#xA7 .. #xA8)
;;; © .. « (#xA9 .. #xAB)
;;; ¬ (#xAC)
;;; ­ .. ¯ (#xAD .. #xAF)
;;; ° .. ± (#xB0 .. #xB1)
;;; ² .. ³ (#xB2 .. #xB3)
;;; ´ (#xB4)
;;; µ (#xB5)
;;; ¶ (#xB6)
;;; · .. Ö (#xB7 .. #xD6)
;;; × (#xD7)
;;; Ø .. ö (#xD8 .. #xF6)
;;; ÷ (#xF7)
;;; ø .. ĉ (#xF8 .. #x109)
;;; Ċ .. ċ (#x10A .. #x10B)
;;; Č .. ď (#x10C .. #x10F)
;;; Đ (#x110)
;;; đ .. ē (#x111 .. #x113)
;;; Ĕ .. ė (#x114 .. #x117)
;;; Ę .. ĝ (#x118 .. #x11D)
;;; Ğ .. ģ (#x11E .. #x123)
;;; Ĥ .. ĥ (#x124 .. #x125)
;;; Ħ (#x126)
;;; Ǻ .. Ǽ (#x1FA .. #x1FC)
;;; ǽ (#x1FD)
;;; Ǿ .. ɏ (#x1FE .. #x24F)
;;; ɐ .. ɚ (#x250 .. #x25A)
;;; ɜ (#x25C)
;;; ɞ .. ɡ (#x25E .. #x261)
;;; ɤ .. ɨ (#x264 .. #x268)
;;; ɬ .. ɳ (#x26C .. #x273)
;;; ɵ (#x275)
;;; ɹ .. ɻ (#x279 .. #x27B)
;;; ɽ .. ɾ (#x27D .. #x27E)
;;; ʁ .. ʄ (#x281 .. #x284)
;;; ʈ .. ʎ (#x288 .. #x28E)
;;; ʐ .. ʒ (#x290 .. #x292)
;;; ʔ .. ʕ (#x294 .. #x295)
;;; ʘ (#x298)
;;; ʝ (#x29D)
;;; ※ (#x203B)
;;; ‿ (#x203F)
;;; ⁂ (#x2042)
;;; ⁇ .. ⁉ (#x2047 .. #x2049)
;;; ⁑ (#x2051)
;;; € (#x20AC)
;;; ℃ (#x2103)
;;; ℏ (#x210F)
;;; ℓ (#x2113)
;;; № (#x2116)
;;; ℡ (#x2121)
;;; ℧ (#x2127)
;;; Å (#x212B)
;;; ℵ (#x2135)
;;; ⅓ .. ⅕ (#x2153 .. #x2155)
;;; Ⅰ .. Ⅻ (#x2160 .. #x216B)
;;; ⅰ .. ⅻ (#x2170 .. #x217B)
;;; ← .. ↓ (#x2190 .. #x2193)
;;; ↖ .. ↙ (#x2196 .. #x2199)
;;; ⇄ (#x21C4)
;;; ⇒ (#x21D2)
;;; ⇔ (#x21D4)
;;; ⇦ .. ⇩ (#x21E6 .. #x21E9)
;;; ∀ (#x2200)
;;; ∂ .. ∃ (#x2202 .. #x2203)
;;; ∅ (#x2205)
;;; ∇ .. ∈ (#x2207 .. #x2208)
;;; ∋ (#x220B)
;;; − (#x2212)
;;; √ (#x221A)
;;; ∝ .. ∞ (#x221D .. #x221E)
