context.exec = [
	{ path = "pactl" args = "load-module module-loopback source=alsa_input.usb-0c76_USB_PnP_Audio_Device-00.iec958-stereo sink_input_properties=media.name=computer-0" }
	{ path = "pactl" args = "set-source-volume alsa_input.usb-0c76_USB_PnP_Audio_Device-00.iec958-stereo 70%" }
	{ path = "pactl" args = "load-module module-loopback source=alsa_input.usb-0c76_USB_PnP_Audio_Device-00.2.iec958-stereo sink_input_properties=media.name=computer-1" }
	{ path = "pactl" args = "set-source-volume alsa_input.usb-0c76_USB_PnP_Audio_Device-00.2.iec958-stereo 70%" }
	{ path = "pactl" args = "load-module module-loopback source=alsa_input.usb-0c76_USB_PnP_Audio_Device-00.3.iec958-stereo sink_input_properties=media.name=computer-2" }
	{ path = "pactl" args = "set-source-volume alsa_input.usb-0c76_USB_PnP_Audio_Device-00.3.iec958-stereo 70%" }
]
