context.exec = [
	{ path = "pactl" args = "load-module module-loopback source=alsa_input.pci-0000_0d_00.4.analog-stereo" }
	{ path = "pactl" args = "set-source-volume alsa_input.pci-0000_0d_00.4.analog-stereo 10%" }
]
