context.exec = [
	{ path = "pactl" args = "load-module module-loopback source=alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_Play__3_YDSB1730337002590Y-00.analog-stereo sink_input_properties=media.name=windows11" }
	{ path = "pactl" args = "set-source-volume alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_Play__3_YDSB1730337002590Y-00.analog-stereo 70%" }
]
